version: "4"

services:

  smart-community :
    image: anshshr/smart-community  
    ports:
      - 3000:3000  
  prom-server:
    image: prom/prometheus
    ports:
      - 9090:9090

  grafana-server:
    image: grafana/grafana
    ports:
      - 3001:3000
